name: unittest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install https://download.pytorch.org/whl/nightly/cu102/torch-1.8.0.dev20201011-cp38-cp38-linux_x86_64.whl
          pip install https://download.pytorch.org/whl/nightly/cu102/torchvision-0.8.0.dev20201011-cp38-cp38-linux_x86_64.whl
          pip install gym wandb matplotlib opencv-python cpprb parameterized akro
      - name: Test with unittest
        run: |
          python -m unittest discover tests
